ADR_CE = 0x10
ADR_WP = 0x20
ADR_CL = 0x40
ADR_AL = 0x80

NAND_CMD_READ = 0x00
NAND_CMD_READCONFIRM = 0x30
NAND_CMD_RNDOUT = 5
NAND_CMD_PROGCONFIRM = 0x10
NAND_CMD_ERASE = 0x60
NAND_CMD_STATUS = 0x70
NAND_CMD_STATUS_MULTI = 0x71
NAND_CMD_PROG = 0x80
NAND_CMD_RNDIN = 0x85
NAND_CMD_READID = 0x90
NAND_CMD_ERASECONFIRM = 0xd0
NAND_CMD_PARAM = 0xec
NAND_CMD_RESET = 0xff


NAND_STATUS_FAIL = (1<<0) # HIGH - FAIL,  LOW - PASS
NAND_STATUS_IDLE = (1<<5) # HIGH - IDLE,  LOW - ACTIVE
NAND_STATUS_READY = (1<<6) # HIGH - READY, LOW - BUSY
NAND_STATUS_NOT_PROTECTED = (1<<7) # HIGH - NOT,   LOW - PROTECTED
